[credentials]
account = "gqfmaui-pb02978"
user = "USER_APP"
warehouse = "WH_USER_APP"
database = "DB_USER_APP"
schema = "PUBLIC"
role = "ROLE_USER_APP"
private_key_path = "/Users/AN20092702/cert/rsa_private_key.p8"
