[credentials]
account = "ist-apdwhdev"
user = "ANIL_VALOOR@APPLE.COM"
warehouse = "DEV_DWH_QUERY_WH"
database = "DEV_ADS_DWH"
schema = "IDS_CSR"
role = "U2320622388_USER_ROLE"
private_key_path = "/Users/AN20092702/cert/rsa_key.p8"